name: Artefact final de JPetStore

on: [push, pull_request]

jobs:
  construire:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Récupérer le code
        uses: actions/checkout@v4

      - name: 2. Installation de Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 3. Compilation (Génère le fichier .war)
        # On demande à Maven de scanner tous les dossiers pour trouver le pom.xml
        run: mvn clean package -DskipTests -f **/pom.xml

      - name: 4. Sauvegarder l'artefact
        uses: actions/upload-artifact@v4
        with:
          name: jpetstore-package
          path: "**/target/*.war"
